security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuarios
                property: email  

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            # Configuración de formulario de login
            form_login:
                login_path: app_login  
                check_path: app_login  
                username_parameter: email  
                password_parameter: password  

            # Configuración de logout
            logout:
                path: app_logout  
                target: homepage  
                
    access_control:
        # Control de acceso para rutas específicas
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Proteger rutas que requieran autenticación
        # Modifica o añade más reglas según las rutas y roles de tu aplicación
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
