controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

inicio:
    path: /
    controller: App\Controller\InicioController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

eliminar_clientes:
    path: /clientes/eliminarclientes
    controller: App\Controller\ClientesController::eliminarClientes
    methods: [POST]

eliminar_tareas:
    path: /tareas/eliminar_tareas
    controller: App\Controller\TareasController::eliminarTareas
    methods: [POST]
