controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

inicio:
    path: /
    controller: App\Controller\InicioController::index

eliminar_usuarios:
    path: /usuarios/eliminarusuarios
    controller: App\Controller\UsuariosController::eliminarUsuarios
    methods: ['POST']