controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

inicio:
    path: /
    controller: App\Controller\InicioController::index

eliminar_registros:
    path: /eliminar-registros
    controller: App\Controller\UsuariosController::eliminarUsuarios
    methods: [POST]

eliminar_clientes:
    path: /eliminar-clientes
    controller: App\Controller\ClientesController::eliminarClientes
    methods: [POST]

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

    
app_obtener_estado_usuarios:
    path: '/obtener-estado-usuarios'
    controller: App\Controller\ProyectosController::obtenerEstadoUsuarios
    methods: ['POST']